.Dd August 20, 2014
.Dt VALYRIATEAR 6
.Os "Valyria Tear Manual"
.Sh NAME
.Nm valyriatear
.Nd free 2D J-RPG based on the Hero of Allacrost engine
.Sh SYNOPSIS
.Nm valyriatear
.Op options
.Sh DESCRIPTION
Valyria Tear is a free (as in the GNU General Public License) 2D
J-RPG game based on the Hero of Allacrost engine.
.Pp
You can play it very much like a typical console role-playing game.
You can explore maps and talk to non-playable characters (NPCs),
fight active-time battles against multiple enemies,
and manage your characters and equipment through a series of menus.
Valyria Tear runs in a series of
.Dq game modes
which represent different states of operation in the game.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c , Fl Fl check
Checks all files for integrity
.It Fl d , Fl Fl debug Ar args
enables debug statements in specified sections of the program,
where
.Ar args
can be:
.Cm all , audio , battle , boot , data , global , input , map ,
.Cm mode_manager , pause , quit , scene , system , utils , video
.It Fl Fl disable-audio
Disables loading and playing audio
.It Fl h , Fl Fl help
Prints the help menu
.It Fl i , Fl Fl info
Prints information about the user's system
.It Fl r , Fl Fl reset
Resets game configuration to use default settings
.El
.Sh GAME INPUT
Valyria Tear players can input commands to the game either through the keyboard
or a gamepad/joystick.
Mouse input is not supported.
.Pp
The table below lists the standard set of user input commands,
their default keyboard mappings, and their general purpose.
.Pp
Most of these keys can be re-mapped from the Valyria Tear main menu
(the boot screen you see when first starting Valyria Tear).
.Bl -tag -width "Right Arrow"
.It Cm "Up Arrow"
Move sprite or cursor upwards
.It Cm "Down Arrow"
Move sprite or cursor downwards
.It Cm "Left Arrow"
Move sprite or cursor to the left
.It Cm "Right Arrow"
Move sprite or cursor to the right
.It Cm F
Confirm an action, interact, or menu command
.It Cm D
Cancel an action or menu command
.It Cm S
Display the party menu
.It Cm Spacebar
Pause/unpause the game
.It Cm Escape
Show the option menu, quit the game in the main menu
.El
.Sh AUTHOR
.An -nosplit
Written by
.An Yohann Ferreira
and
.An Erik Schilling .
.Sh REPORTING BUGS
Report bugs to
.Lk https://github.com/Bertram25/ValyriaTear/issues .
.Sh COPYRIGHT
Copyright \(co 2012-2014 Valyria Tear Development Team.
License
.Lk "GPLv2: GNU GPL version 2" https://www.gnu.org/licenses/gpl-2.0.html .
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
